import sys
import os
import django

sys.path.append("/c/Users/HP1/Desktop/Our Library Django/God's Library/libraryofgod")
os.environ['DJANGO_SETTINGS_MODULE'] = 'libraryofgod.settings'
django.setup()



########### START ####################
print("starting..................")
print("*****************************")
print("Deleting Previous Data")

from books.models import Person, Book, Wish

### DELETE ###
Person.objects.all().delete()
Book.objects.all().delete()
Wish.objects.all().delete()

print("Done Deleting ALL Data")

print("***************************")
print("Adding People:")
persons = [
    'Elizebeth Stotz',
    'Afton Mcquillen',
    'Valarie Pinelli',
    'Shane Ross',
    'Celina Ferrer',
    'Waneta Storrs',
    'Elida Mcroy',
    'Cathie Marshall',
    'Lavern Kreger',
    'Ghislaine Yankey',
    'Jenice Oberg',
    'Lanie Nolen',
    'Ammie Meade',
    'Fern Joseph',
    'Lindy Bisignano',
    'Lashawn Moran',
    'Asa Baize',
    'Luz Woodie',
    'Adelia Vail',
    'Latoyia Saulnier',
    'Judi Sarcone',
    'Mac Brandi',
    'Ingeborg Wedderburn',
    'Clemencia Zucco',
    'Madeline Crabb',
    'Melodee Akin',
    'Violet Forbis',
    'Linnea Maslowski',
    'Fay Vila',
    'Hermine Moose',
    'Tiffani Tumlin',
    'Kristian Crapo',
    'Miguelina Lamantia',
    'Athena Haswell',
    'Alfreda Bookout',
    'Julienne Rueda',
    'Roxy Satterwhite',
    'Angelyn Pigott',
    'Genesis Herriott',
    'Dusti Pintor',
    'Kenton Norfleet',
    'Shira Marth',
    'Winston Carrol',
    'Ross Delph',
    'Tijuana Horstmann',
    'Ona Heatley',
    'Holly Kistner',
    'Ezekiel Wagner',
    'Dudley Moroney',
    'Letisha Lobato',
    'Malorie Bera',
    'Chantal Molnar',
    'Fredia Folger',
    'Zandra Simonton',
    'Vi Spinney',
    'Carisa Luick',
    'Stanford Natali',
    'Alonzo Ottesen',
    'Art Rinaldo',
    'Flavia Whittenburg',
    'Leigha Benedetti',
    'Eleni Ratner',
    'Danille Deibler',
    'Niesha Weekley',
    'Akiko Grissett',
    'Minna Schanz',
    'Dorie Spraggs',
    'Tamie Kittrell',
    'Herschel Bardsley',
    'Susanna Ault',
    'Ardelle Monnin',
    'Willette Rotz',
    'Fae Whetsel',
    'Teressa Maysonet',
    'Zola Yaple',
    'Merrilee Fehrenbach',
    'Erwin Fitting',
    'Ernest Hymer',
    'Demetria Dowler',
    'Felix Lyons',
    'Shanon Zeiger',
    'Nicki Pilot',
    'Yvonne Blatt',
    'Katherine Wengert',
    'Latonia Holbrook',
    'Verla Arocha',
    'Kit Webb',
    'Na Haase',
    'Clemente Hiney',
    'Ethel Hubbs',
    'Lajuana Shoemaker',
    'Manual Aitchison',
    'Leonore Kary',
    'Elvina Brizendine',
    'Donella Seigler',
    'Philip Fell',
    'Dusti Porras',
    'Shawn Hamner',
    'Gladys Pressley',
    'Walton Eads',
]

persons_list = []
for person in persons:
    p = Person(name=person)
    p.save()
    persons_list.append(p)

print("Done Loading People Data")
print("#######################################")

print("Adding Books")
books = [
    'Win Friends and Influence People',
    'Rich Dad Poor Dad',
    'Quiet',
    'Arthatantra',
    'All of me',
    'Algorithms to live by',
    'Sapiens A brief history of Humankind',
    '21 lessons for the 21st Century',
    'Awakening the Sleeping Slef',
    'Our Mathematical Universe',
    'Weapons of Math Destruction',
    '1991 Fatalism and Development Nepals Struggle of Modernization by Bista s',
    '21 Lessons for the 21st Century by Yuval Noah Harari',
    '536',
    'A Mind for Numbers   Barbara Oakley',
    'A World of Three Zeros   Muhammad Yunus',
    'a guide to the project management body of knowledge',
    'Abundance The Future Is Better Than You Think   Peter Diamandis',
    'Accessory to War The Unspoken Alliance Between Astrophysics',
    'Actionable Gamification by Yu kai Chou',
    'agile scrum',
    'Art of Logic in an Illogical World by Eugenia Cheng',
    'Art problem solving',
    'Astrophysics for People in a Hurry   Neil deGrasse Tyson',
    'AWAKEN THE GIANT WITHIN',
    'Aware by Dr. Daniel J. Siegel',
    'Behave   The Biology of Humans at Our Best and Worst',
    'Big Debt Crises   Ray Dalio',
    'Bitwise   David Auerbach',
    'Blender Hotkeys Cheatsheet',
    'Blender Documentation',
    'Blender Hotkey Reference',
    'Brief Answers to the Big Questions   Stephen Hawking',
    'Built The Hidden Stories Behind our Structures   Roma Agrawal',
    'coding standards',
    'Enlightenment Now  The Case for Reason   Steven Pinker',
    'Everything All at Once   Bill Nye',
    'Game Dev Timeline',
    'God   A Human History   Reza Aslan',
    'Guns, Germs, and Steel   Jared Diamond',
    'Hamming TheArtOfDoingScienceAndEngineering',
    'Hidden Figures   Margot Lee Shetterly',
    'Hit Refresh   Satya Nadella',
    'Homo Deus  A Brief History of Tomorrow   Yuval Noah Harari',
    'How to Be a Good Creature by Sy Montgomery',
    'How to Be a Stoic   Massimo Pigliucci',
    'How To Think   Alan Jacobs',
    'How to Transform Your Life',
    'IntelliJIDEA ReferenceCard',
    "It's All Relative   A. J. Jacobs",
    'Kitchen Confidential   Anthony Bourdain',
    'Know This   Mr. John Brockman',
    'liespotting   proven techniques to detect   pamela meyer',
    'Life in Code   Ellen Ullman',
    'Little Book of Contentment',
    'Lucid Dreaming Induction Techniques',
    'Mastering PowerShell',
    'Measure What Matters   John Doerr',
    'On Trails  An Exploration   Robert Moor',
    'Our Mathematical Universe  My Quest for the Ultimate Nature of Reality   Max Tegmark',
    'Pragmatic Guide to Sass',
    'Relational Databases',
    'Richard Dawkins   The God Delusion',
    'Ruby on Rails Tutorial, 2nd Edition',
    'Same Kind Of Different As Me   Ron Hall, Denver Moore',
    'Spineless   Juli Berwald',
    'Stephen Wolfram A New Kind of Science Wolfram Media (2002)',
    'stephen hawking the grand design',
    'The Case Against Sugar   Gary Taubes',
    'The Cast Against Education   Bryan Caplan',
    'The Equations of Life   Charles S. Cockell',
    'The Four The Hidden DNA of Amazon, Apple, Facebook, and Google by Scott Galloway',
    'The Four Dimensional Human   Laurence Scott',
    'The Great Unknown   Marcus du Sautoy',
    'The Knowledge Illusion   Steven Sloman',
    'The Last Man Who Knew Everything   David N. Schwartz',
    'The One Device   Brian Merchant',
    'The Order of Time   Carlo Rovelli',
    'The Perfectionists   Simon Winchester',
    'The Power of Habit   Charles duhigg',
    'The Social Leap   William von Hippel',
    'The Tangled Tree  A Radical New History of Life  Quammen, David',
    'The Undoing Project  A Friendship That Changed Our Minds  Michael Lewis',
    'The Wizard and the Prophet   Charles C. Mann',
    'The 48 Laws of Power',
    'the 80 20 principle to achieve more with less effort1',
    'the art of seduction robert greene',
    'the world without us by alan weisman',
    'Thing Explainer  Complicated Stuff In Simple Words   Randall Munroe',
    'To Shake the Sleeping Self by Jedidiah Jenkins',
    'Tribe of Hackers   Marcus J. Carey',
    'Walter Lewin, Warren Goldstein For the Love of Physics  From the End of the Rainbow to the Edge Of Time   A Journey Through the Wonders of Physics Free Press (2011)',
    'Weapons of Math Destruction   Cathy O Neil',
    'What If This Were Enough Essays by Heather Havrilesky',
    'what if serious scientific answers to absurd hypothetical questions',
    'When The Scientific Secrets by Daniel H. Pink',
    'When Breath Becomes Air   Paul Kalanithi',
    'Who Can You Trust   Rachel Botsman',
    'Why You Eat What You Eat by Rachel Herz',
    'You Can Fix Your Brain by Tom OBryan'
]
books_list = []
for book, person in zip(books, persons_list):
    b = Book(name=book, owner=person)
    b.save()
    books_list.append(b)

print("Done Loading Book Data")
print("#######################################")

print("Adding Wishes")
wish_orders = [
    [6, 2, 4],
    [5, 1, 6],
    [5, 4, 6],
    [1, 2, 3],
    [1, 2, 3],
    [1, 4, 5],
    [71, 82, 12, 46, 13],
    [35, 0],
    [16, 96, 35],
    [98, 99, 17, 45, 31],
    [23, 34, 19, 87, 16, 0],
    [57, 54],
    [56, 26, 4],
    [48, 81],
    [70, 51, 95, 96, 69, 70],
    [29, 25, 1, 52, 81, 16],
    [77, 41],
    [93, 8, 95],
    [87, 84, 6, 68, 67],
    [14, 87, 89, 85, 11, 29],
    [96, 17, 83, 47, 79],
    [27, 9],
    [73, 54, 35, 39],
    [85, 22],
    [80, 3, 3],
    [78, 78, 76, 17, 8, 29],
    [18, 85, 64, 50, 80],
    [21, 1, 16],
    [50, 96, 26, 39, 6],
    [57, 82],
    [11, 67],
    [15, 69, 83, 26, 45, 16],
    [95, 24],
    [83, 27, 27],
    [62, 7],
    [41, 88],
    [2, 87, 76, 25, 21, 92],
    [36, 61],
    [51, 25, 47, 69],
    [82, 84, 29, 87, 8],
    [73, 1, 70, 99, 31, 18],
    [96, 69, 41, 38, 90, 15],
    [91, 78],
    [50, 38],
    [47, 1, 40, 28, 11, 76],
    [8, 10],
    [89, 33],
    [36, 66, 30, 78, 96],
    [55, 98, 95, 23],
    [39, 25, 34, 66, 93, 88],
    [45, 96],
    [71, 6, 68],
    [20, 88, 33, 50],
    [61, 98, 27, 68, 90],
    [14, 95, 85, 25, 34],
    [0, 48],
    [69, 60],
    [69, 2, 31],
    [82, 29, 25, 58, 9],
    [53, 85, 76, 68, 29, 77],
    [66, 42],
    [34, 1],
    [85, 69],
    [51, 52],
    [75, 86],
    [77, 45, 39, 50, 94, 73],
    [64, 48, 31, 85, 52, 96],
    [98, 92, 15, 67],
    [50, 31, 37, 59, 41, 57],
    [77, 20, 14, 84, 47, 4],
    [66, 47, 91, 17],
    [61, 70, 60, 69, 68],
    [85, 99, 66, 95, 0],
    [50, 77],
    [54, 43],
    [90, 50, 18],
    [22, 70, 82, 77, 71],
    [81, 90, 6, 17, 49, 44],
    [25, 94, 69, 15, 7],
    [97, 12],
    [37, 20],
    [23, 81, 83, 4, 83],
    [55, 74],
    [28, 38, 99, 86, 23, 51],
    [46, 5, 77],
    [79, 35],
    [46, 62, 61, 58, 90, 17],
    [98, 93, 64, 94, 92, 56],
    [76, 32],
    [36, 89],
    [94, 61],
    [7, 8, 40, 49],
    [10, 70, 41, 10, 2, 44],
    [29, 51, 44, 70, 5],
    [73, 39, 35],
    [9, 75, 59],
    [95, 42, 68],
    [28, 4, 32],
    [89, 41, 93, 72, 66],
    [26, 24],
]

# for i, wish_order in enumerate(wish_orders):
for wish_order, wisher in zip(wish_orders, persons_list):
    for rank, j in enumerate(wish_order):
        book = books_list[j]
        angel = book.owner
        wish = Wish(book=book, wisher=wisher, angel=angel, rank=rank)
        wish.save()

print("Done Adding Wishes for everyone")
