# Generated by Django 2.2 on 2019-04-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='current_owner',
        ),
        migrations.AddField(
            model_name='person',
            name='owned_books',
            field=models.ManyToManyField(blank=True, related_name='owners', to='books.Book'),
        ),
    ]
