# Generated by Django 2.2 on 2019-04-11 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_b_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last',
        ),
        migrations.RemoveField(
            model_name='person',
            name='owned_books',
        ),
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='Mr Nobody', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default='Invisible Book', max_length=20),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='B',
        ),
        migrations.DeleteModel(
            name='P',
        ),
    ]
