# Generated by Django 2.2 on 2019-04-11 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190411_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fulfilled', models.BooleanField(default=False)),
                ('desire_lvl', models.IntegerField(default=1)),
                ('angel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishes_fulfilled', to='books.Person')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='books.Book')),
                ('wisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='books.Person')),
            ],
        ),
    ]
