# Generated by Django 2.2 on 2019-04-15 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='desire_lvl',
            new_name='rank',
        ),
    ]
