# Generated by Django 2.2 on 2019-04-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190415_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting', models.BooleanField(default=False)),
                ('king', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='king_exchanges', to='books.Person')),
                ('queen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queen_exchanges', to='books.Person')),
            ],
        ),
    ]
