# Generated by Django 2.2 on 2019-04-17 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='kingbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kingbook_exchanges', to='books.Book'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='queenbook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queenbook_exchanges', to='books.Book'),
        ),
    ]
